### ISSUE TITLE
Dependencies too restrictives

### ISSUE THREAD

**Issue by RobinDavid** [quarkslab/quokka#18]
Quokka setup.py defines the following dependencies:

* capstone>=4.0.2,<5,
* networkx>=2.4,<3,
* protobuf>=3.12.2,<4,
* pypcode>=1.1.1,<2,

As capstone 5.0.0 is now released, it makes quokka incompatible with latest capstone version. I am wondering why we purposely restricted the maximum version. I suggest:

* removing max version enforcement (unless truly incompatible)
* removing pypcode as a mandatory dependency. It brings **a lot** of additional dependencies and is not used in most Quokka usages. Thus I'd suggest moving it as extra_require, and  importing it when being used (and failing nicely if it is not installed).

**Comment by DarkaMaul** [comment]
>  I am wondering why we purposely restricted the maximum version. I suggest:

The idea here is to make sure we don't introduce a breaking change in Quokka before it has been tested. If the dependency follows semantic versioning best practices, it guarantees that incompatible API change only occur during major version update ( exactly those who are prevented by this requirement).

> removing pypcode as a mandatory dependency

I completely agree here :)
